<?php include "header.php"; ?>
<!-- this content was generated by AI -->
<div id = "aboutUs">
    <h1>Modest Boutique</h1>
    <h2>A Haven of Modesty and Style</h2>
    <p>At <em>Modest Boutique<em>, we believe that modesty is paramount. Our boutique is a haven 
        for women seeking elegant, modest clothing that reflects their unique personality and values.</p>

    <h3>Our Mission:<h3>
    <p>To empower women to feel confident and beautiful in their clothing, while adhering to their religious and cultural beliefs.<p>

    <h3>What We Offer:</h3>
    <ul>
        <li>A curated selection of modest clothing, including dresses, skirts, tops, and more.</li>
        <li>High-quality fabrics and impeccable craftsmanship.</li>
        <li>A welcoming and personalized shopping experience.</li>
        <li>Expert style advice to help you find the perfect outfit.</li>
    </ul>
    
    <h3>Our Story:</h3>
    <p><em>Modest Boutique</em> was founded by Bluma Rodkin, a computer science major with a passion for modest fashion and software development.
    Inspired by a variety of things, we strive to create a shopping experience that is both stylish and meaningful.
    </p>

    <h3>Visit Us Today:</h3>
    <p>We invite you to visit our boutique in Far Rockaway to discover our latest collections and experience our warm hospitality.</p>

    <h3>We love to hear from you:</h3>
    <p>Please let us know what's on your mind!</p>
    <p>We welcome your comments, compliments, ideas or even criticism.</p>
    <p>We're all about you. Teach us how best to help you.</p>
    <p><a href = "contact.php">Contact us</a> today.</p>

</div>

<?php include "footer.php"; ?>